### ISSUE TITLE
漏了写一些东西(

### ISSUE THREAD

**Issue by ClearZer0** [Saplonily/CelesteModTourial#1]
基础环境配置,添加 Module 类没写要继承EverestModule类,还有Celeste.Mod的引用

**Comment by Saplonily** [comment]
好好好(, 加粗了https://github.com/Saplonily/CelesteModTourial/blob/master/docs/begin/BasicEnv.md#%E6%B7%BB%E5%8A%A0-module-%E7%B1%BB
